# Generated by Django 2.0.5 on 2018-05-17 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0002_pizza_maker'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
